# SPDX-License-Identifier: GPL-3.0-or-later

version: 2
updates:
- package-ecosystem: cargo
  directory: "/common_items"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: cargo
  directory: "/bootx64"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: cargo
  directory: "/kernel"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
