language:
  rust

rust:
  - nightly

addons:
  apt:
    packages:
      - nasm
      - mtools

install:
  - rustup component add rust-src
  - sudo apt install qemu ovmf
  - cp /usr/share/OVMF/OVMF_* .

script:
  - make test
  - make release_test
