language:
    rust

rust:
    - nightly

addons:
    apt:
        packages:
            - nasm

before_install:
    - cargo install cargo-xbuild
    - rustup component add rust-src

install:
    - make
