[package]
name = "ramen"
version = "0.1.0"
authors = ["toku-sa-n <tokuchan3515@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 0

# I don't know why lto = false causes some problems like not print the correct words on the screen.
lto = true
panic = "abort"

[profile.release]
opt-level = 3
lto = true
panic = "abort"

[lib]
name = "ramen_os"
crate-type = ["staticlib"]

[dependencies]
