[package]
name = "ramen"
version = "0.3.0"
authors = ["toku-sa-n <tokusan441@gmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"

[features]
default = []
qemu_test = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 0

# I don't know why lto = false causes some problems like not print the correct words on the screen.
lto = true

[profile.release]
opt-level = 3
lto = true

[lib]
name = "ramen_os"
crate-type = ["staticlib"]
test = false
bench = false

[dependencies]
common = { path = "../common" }
conquer-once = { version = "0.2.1", default-features = false }
spinning_top = "0.2.2"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
qemu-exit = "0.1.3"
x86_64 = "0.11.4"
