name: clippy

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly
          components: clippy
          override: true

      - name: Run clippy for the kernel code
        run: |
          cd kernel
          cargo clippy

      - name: Run clippy for bootx64.efi code
        run: |
          cd bootx64
          cargo clippy

      - name: Run clippy for common crate
        run: |
          cd common
          cargo clippy
