name: Rust

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2

    - name: Install rust nightly
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
        components: rust-src, clippy
        override: true

    - name: action-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install dependencies
      run: sudo apt-get install nasm mtools qemu ovmf

    - name: Copy OVMF_*
      run: cp /usr/share/OVMF/OVMF_* .

    - name: Test on debug mode
      timeout-minutes: 5
      run: make test

    - name: Test on release mode
      timeout-minutes: 5
      run: make release_test
